import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Typewriter from "typewriter-effect"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">KULKUL</a>
        </h1>

        <p className={styles.description}>
          Get started by registering your{' '}
            <Typewriter
              options={{
                loop: true,
                autoStart: true,
                strings: ["fridge", "food", "recipe"],
              }}
            />
        </p>

        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>Fridges &rarr;</h2>
            <p>View all your fridges in one place, including their contents.</p>
          </a>

          <a href="" className={styles.card}>
            <h2>Login &rarr;</h2>
            <p>Hop into your account before managing your provisions!</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Recipes &rarr;</h2>
            <p>Explore various recipes previously acquired and expand it.</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Expiry &rarr;</h2>
            <p>
              Keep track of expiration dates and be notified for close to expiring items.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://mdzkm.netlify.app/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright © 2022 mdzkm. All Rights Reserved
        </a>
      </footer>
    </div>
  )
}

export default Home
